Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello"
 
  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/bionic64"
	web01.vm.network "private_network", ip: "192.168.33.19"
	web01.vm.provider "virtualbox" do |vb|
	 vb.memory = "1024"
	 vb.cpus = 2
  end
  web01.vm.provision "shell", inline: <<-SHELL
    yum install httpd wget unzip -y
    systemctl start httpd
    systemctl enable httpd
    cd /tmp/
    wget https://www.tooplate.com/zip-templates/2106_soft_landing.zip
    unzip -o 2106_soft_landing.zip
    cp -r 2106_soft_landing/* /var/www/html
    systemctl restart httpd
     
   SHELL
  end
 
  config.vm.define "db01" do |db01|
    db01.vm.box = "cento/7"
	db01.vm.network "private_network", ip: "192.168.33.20"
	db01.vm.provider "virtualbox" do |vb|
	 vb.memory = "1024"
	 vb.cpus = 2
  end
	db01.vm.provision "shell", inline: <<-SHELL
	yum install mariadb-server -y
	systemctl start mariadb
	systemctl enable mariade
	
	mysql -u root -e "CREATE DATABASE wordpress;"
	mysql -u root -e "GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER ON wordpress.* TO wordpress@localhost;"
	mysql -u root -e "FLUSH PRIVILEGES;"
	SHELL
  end
end